column_rename_map = {
        "name": "Name",
        "distance": "Distance (km)",
        "moving_time": "Moving Time (s)",
        "elapsed_time": "Elapsed Time (s)",
        "total_elevation_gain": "Elevation Gain (m)",
        "sport_type": "Sport Type",
        "start_date_local": "Start Date",
        "average_speed": "Average Speed (km/h)",
        "max_speed": "Max Speed (km/h)",
        "average_cadence": "Average Cadence (rpm)",
        "average_watts": "Average Watts",
        "max_watts": "Max Watts",
        "kilojoules": "Energy (kJ)",
        "average_heartrate": "Average Heart Rate (bpm)",
        "max_heartrate": "Max Heart Rate (bpm)",
        "elev_high": "Max Elevation (m)",
        "elev_low": "Min Elevation (m)",
        "map": "Map",
    }